### ISSUE TITLE
Multi async call are not handle with jest-chain

### ISSUE THREAD

**Issue by othke** [mattphillips/jest-chain#32]
<!--
**Bug**

- `package` version:
-  "jest": "26.6.3"
- "jest-chain": "1.1.5"
- "ts-jest": "26.5.6"
- "jest-cli": "26.6.3",
- `node` version: 14.16.0
- `npm` version:  6.14.11

**What you did:**
I just add this simple test where I need to check how many times an async function has been called

```typescript
// helpers.ts
export const wait = () => Promise.resolve()
```

```typescript
// index.ts
import { wait } from "./helpers"

export const doSomething = async () => {
  await wait()
  await wait()
  await wait()
  await wait()
  await wait()
  await wait()
  return 'foo' as any
}
```

```typescript
// index.test.ts
import * as helpers from "./helpers";
import { doSomething } from "./index";

describe("index", () => {
  afterEach(() => {
    jest.resetAllMocks();
  });

  describe("try doSomething with multi called", () => {
    let spyOnWait: any;
    beforeEach(() => {
      spyOnWait = jest
        .spyOn(helpers, "wait");
    });
    it("should make multi called to async wait", async () => {
      await expect(doSomething()).resolves.toEqual("foo");
      expect(spyOnWait).toHaveBeenCalledTimes(6);
    });
  });
});
```

```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFilesAfterEnv: ["jest-chain"]
};
````

**What happened :**

If I let jest-chain

```javascript
// jest.config
 FAIL  src/lib/index.test.ts
  index
    try doSomething with multi called
      ✕ should make multi called to async wait (6 ms)

  ● index › try doSomething with multi called › should make multi called to async wait

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 6
    Received number of calls: 2

      15 |     it("should make multi called to async wait", async () => {
      16 |       await expect(doSomething()).resolves.toEqual("foo");
    > 17 |       expect(spyOnWait).toHaveBeenCalledTimes(6);
         |                         ^
      18 |     });
      19 |   });
      20 | });

      at src/lib/index.test.ts:17:25
      at fulfilled (src/lib/index.test.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
````

If I let `jest-chain`

If I remove `jest-chain`
```js
 PASS  src/lib/index.test.ts
  index
    try doSomething with multi called
      ✓ should make multi called to async wait (4 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
```

If I execute the promise outside of the expect and store the result everything works

```typescript
    it("should make multi called to async wait", async () => {
      const result = await doSomething()
      expect(result).toEqual("foo");
      expect(spyOnWait).toHaveBeenCalledTimes(6);
    });
````

**Comment by mattphillips** [comment]
Hey @othke are you able to provide a repro of this? 

I think this is working as of https://www.npmjs.com/package/jest-chain/v/1.1.6 but feel free to reopen if the issue is still present.
